name: Release

on: [issues]

jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - name: Release
      uses: cermakm/python-release-action@experimental
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Whether to generate changelog
        changelog: true
