name: Release

on: [issues, issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"

    
    - name: Release
      uses: cermakm/python-release-action@experimental
      with:
        # Whether to generate changelog
        changelog: true
