name: Release

on:
  push:
    branches:
    - release-*

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build, and test
      run: |
        pushd js/
        npm install
        npm run build-prod --if-present
        npm test
        popd
      env:
        CI: true

    - name: Setup environment
      run: |
        pip install .
        pip install twine semantic_version

    - name: Release
      run: |
        git config --local user.name  "Marek Cermak"
        git config --local user.email "macermak@redhat.com"

        make release  # generates CHANGELOG and a new tag from the release branch

        git push
          --follow-tags \
          "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" \
          "HEAD:${{ github.ref }}"
